# Generated by Django 4.0.6 on 2022-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_foodlist_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='item_image',
            field=models.CharField(default='https://www.kindpng.com/picc/m/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png', max_length=500),
        ),
    ]
